input {
  http {
    host => "0.0.0.0"
    port => 8080
    codec => json
  }
}

filter {
  if ![environment] or ![environment_name] {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "frontiercloud-%{[environment]}-%{+YYYY.MM}"
  }
}
