[package]
name = "frontier-karaoke-api-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
frontier-karaoke-core = { path = "../frontier-karaoke-core" }
serde.workspace = true
serde_json.workspace = true
serde-wasm-bindgen = "0.6.5"
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
js-sys.workspace = true
web-sys = { workspace = true, features = ["Headers", "Request", "RequestInit", "RequestMode", "Response", "Window"] }
